# Listas de competidores por mercado/categoría (España)
# Estas listas se usan para poblar la BD de marcas por categoría.
# El análisis usará TODAS las marcas; los gráficos se limitarán a top 6-7.

markets:
  - categoria: "Chocolates Premium/Gourmet"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Lindt"
      - "Godiva"
      - "Valrhona"
      - "Neuhaus"
      - "Simón Coll / Amatller"
      - "Blanxart"
      - "Kaitxo"
      - "Utopick Chocolates"
      - "Puchero"
      - "Chocolates Trapa (gama premium)"
      - "Valor (gama premium/orígenes)"
      - "Nestlé Les Recettes de l'Atelier"
      - "Ferrero Rocher / Ferrero Collection"
      - "Guylian"
      - "Faborit"
      - "Cacao Sampaka"
      - "Pancracio"
      - "La Chinata"
      - "Chocolates Torras"
      - "Willie's Cacao"
      - "Michel Cluizel"
      - "Domori"
      - "Pralinés Sant Tirs"
      - "El Corte Inglés (Club del Chocolate)"
      - "Moser Roth (Aldi)"
      - "Leonidas"
      - "Jeff de Bruges"

  - categoria: "Bollería Industrial / Panadería Envasada y Tortitas"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Bimbo"
      - "La Bella Easo"
      - "Dulcesol"
      - "Brioche Pasquier"
      - "La Granja Foods"
      - "Codan"
      - "Panrico"
      - "Bicentury"
      - "Gullón (Vitalday - Tortitas)"
      - "Santiveri"
      - "Gerblé"
      - "Hacendado (Mercadona)"
      - "Carrefour (MDD)"
      - "Dia (MDD)"
      - "Lidl (MDD)"
      - "Alcampo (MDD)"
      - "Eroski (MDD)"
      - "Milka"
      - "Oreo"
      - "Nutella"
      - "Schär"
      - "Panamar Bakery Group"
      - "Europastry"
      - "Horno de San Juan"
      - "Diet Radisson"
      - "Spar (MDD)"
      - "Consum (MDD)"

  - categoria: "Confitería / Turrones y Mazapanes"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Delaviuda"
      - "Suchard (Mondelez)"
      - "1880"
      - "Lacasa"
      - "El Almendro"
      - "Antiu Xixona"
      - "Picornell"
      - "San Andrés"
      - "Turrones Vicens"
      - "Pablo Garrigós Ibáñez"
      - "Hacendado (Mercadona)"
      - "El Corte Inglés (MDD)"
      - "Carrefour (MDD)"
      - "Dia (MDD)"
      - "Lidl (DOR - MDD)"
      - "Eroski (MDD)"
      - "Ferrero"
      - "Lindt"
      - "Virginias"
      - "Mazapanes Barroso"
      - "Mazapanes Conde"
      - "Santo Tomé"
      - "Coloma García"
      - "Turrones José Garrigós"
      - "Enrique Rech"
      - "Monerris Planelles"
      - "Artesanía Castillo de Jijona"

  - categoria: "Ginebras"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Larios"
      - "Beefeater"
      - "Tanqueray"
      - "Seagram's"
      - "Gordon's"
      - "Bombay Sapphire"
      - "Hendrick's"
      - "Gin Mare"
      - "Monkey 47"
      - "Nordés"
      - "Puerto de Indias"
      - "Bulldog Gin"
      - "Martin Miller's"
      - "Plymouth Gin"
      - "G'Vine"
      - "Brockmans"
      - "Citadelle"
      - "Roku Gin"
      - "Gin MG"
      - "Siderit"
      - "Rives"
      - "Macaronesian Gin"
      - "Gin Raw"
      - "Santamanía"
      - "Marcas Blancas (Castelgy, etc.)"
      - "Ampersand"
      - "Master's Gin"

  - categoria: "Galletas Saludables"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Gullón"
      - "Gerblé"
      - "Santiveri"
      - "Bicentury"
      - "Artiach"
      - "Cuétara"
      - "Hacendado (Cuídate)"
      - "Carrefour (Bio / No Sugar)"
      - "Dia (Vital / Sin Azúcares)"
      - "Lidl (MDD Saludable)"
      - "Eroski (Sannia)"
      - "El Corte Inglés (Saludable)"
      - "Schär"
      - "Virginias"
      - "Diet Radisson"
      - "Biocop"
      - "El Granero Integral"
      - "Sol Natural"
      - "Int-Salim"
      - "Verkade"
      - "LU (Harmony)"
      - "Fontaneda"
      - "Digestive (McVitie's)"
      - "Belvita"
      - "Special K"

  - categoria: "Galletas de Café / Speculoos"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Lotus Biscoff"
      - "Hacendado (Speculoos)"
      - "Carrefour (Speculoos)"
      - "Dia (Speculoos)"
      - "Lidl (Sondey Speculoos)"
      - "Eroski (Caramelizadas)"
      - "El Corte Inglés (Caramelizadas)"
      - "Vermeiren"
      - "Poppies"
      - "Albert Heijn (MDD)"
      - "Jules Destrooper"
      - "Daelmans"
      - "Walkers"
      - "Campurrianas (Cuétara)"
      - "Napolitanas (Artiach)"
      - "Bonne Maman"
      - "Bahlsen"
      - "Hoppe"
      - "Galletas La Paz"
      - "Trader Joe's"
      - "Biscoff Spread"
      - "Helados sabor Biscoff"
      - "Marcas de café con galleta"
      - "Starbucks"
      - "Costa Coffee"

  - categoria: "Embutidos Curados (Serrano)"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Campofrío"
      - "ElPozo"
      - "Navidul"
      - "Revilla"
      - "Noel Alimentaria"
      - "Argal"
      - "Palacios Alimentación"
      - "La Hoguera"
      - "Embutidos España"
      - "Hacendado (Mercadona)"
      - "Carrefour (MDD)"
      - "Dia (MDD)"
      - "Lidl (Realvalle / Dulano)"
      - "Eroski (MDD)"
      - "Alcampo (MDD)"
      - "Consum (MDD)"
      - "Incarlopsa"
      - "Grupo Jorge"
      - "Casademont"
      - "Espuña"
      - "Goikoa"
      - "Alejandro Miguel"
      - "Torre de Nuñez"
      - "Boadas 1880"
      - "Embutidos Collell"
      - "Jamones Aljomar"
      - "Nico Jamones"
      - "Redondo Iglesias"

  - categoria: "Rones"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Bacardí"
      - "Havana Club"
      - "Brugal"
      - "Ron Barceló"
      - "Diplomático"
      - "Zacapa"
      - "Ron Abuelo"
      - "Don Q"
      - "Flor de Caña"
      - "Captain Morgan"
      - "The Kraken"
      - "Santa Teresa"
      - "Pampero"
      - "Matusalem"
      - "Cacique"
      - "Negrita"
      - "Legendario"
      - "Arehucas"
      - "Varadero"
      - "Plantation Rum"
      - "Appleton Estate"
      - "Mount Gay"
      - "Ron Montero"
      - "Dos Maderas"
      - "Marcas Blancas (Almirante, etc.)"
      - "Botran"
      - "El Dorado"

  - categoria: "Higiene Personal / Gel de Ducha"
    tipo_mercado: "FMCG"
    pais: "España"
    marcas:
      - "Dove"
      - "Nivea"
      - "Sanex"
      - "Palmolive"
      - "La Toja"
      - "Lactovit"
      - "Magno"
      - "Natural Honey"
      - "Tulipán Negro"
      - "Heno de Pravia"
      - "Fa"
      - "Adidas Body Care"
      - "Axe"
      - "Old Spice"
      - "Moussel"
      - "Deliplus (Mercadona)"
      - "Carrefour (MDD)"
      - "Cien (Lidl)"
      - "Bonté (Dia)"
      - "Eroski (MDD)"
      - "Rituals"
      - "The Body Shop"
      - "L'Occitane"
      - "Yves Rocher"
      - "Weleda"
      - "Dr. Bronner's"
      - "Isdin"
      - "Eucerin"
      - "A-Derma"
      - "Sebamed"
      - "Instituto Español"
      - "Babaria"
      - "Johnson's Baby"
      - "Original Remedies (Garnier)"
      - "Le Petit Marseillais"
