# TwoLaps Intelligence Platform - Global Settings

database:
  # Connection pool settings
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  echo: false  # Set to true for SQL query logging

polling:
  # Default polling interval if not specified
  default_interval_minutes: 60
  # Max concurrent query executions
  max_concurrent_queries: 12
  # Retry settings
  max_retries: 3
  retry_backoff_seconds: 5

llm_providers:
  # Which providers are enabled
  enabled:
    - openai
    - anthropic
    - google
    - perplexity
  
  # Temperature settings by use case
  temperature:
    analysis: 0.3  # Low temperature for factual analysis
    synthesis: 0.5  # Medium for creative synthesis
  
  # Token limits
  max_tokens:
    analysis: 2000
    synthesis: 4000
    executive_summary: 10000  # Aumentado de 6000 a 10000 para informes de nivel consultora
    campaign_analysis: 3000  # NUEVO
    channel_analysis: 3000  # NUEVO
    market_context: 3500  # NUEVO
  
  # Cost tracking
  cost_per_1k_tokens:
    openai:
      gpt-4o:
        input: 0.0025
        output: 0.01
      gpt-4-turbo:
        input: 0.01
        output: 0.03
      text-embedding-3-small:
        input: 0.00002
    anthropic:
      claude-sonnet-4-5:
        input: 0.003
        output: 0.015
    google:
      gemini-1.5-pro-latest:
        input: 0.00125
        output: 0.005
    perplexity:
      sonar-small-online:
        input: 0.001
        output: 0.002
      sonar-medium-online:
        input: 0.002
        output: 0.004

analytics:
  # Analysis parameters
  top_keywords: 30  # Aumentado de 20 a 30 para análisis más rico
  min_keyword_frequency: 2
  sentiment_scale: [-1, 1]  # -1 (negative) to 1 (positive)
  
  # SOV (Share of Voice) settings
  sov:
    min_mentions: 1
    include_indirect: true  # Include indirect mentions
  
  # RAG settings
  rag:
    enabled: true
    top_k_similar: 5  # Aumentado de 3 a 5 periodos históricos para más contexto
    similarity_threshold: 0.70  # Bajado de 0.75 a 0.70 para capturar más contexto relevante
    embedding_model: text-embedding-3-small
  
  # Campaign Analysis settings (NUEVO)
  campaign_analysis:
    min_mentions_for_campaign: 3
    detect_channels: true
    analyze_influencers: true
  
  # Channel Analysis settings (NUEVO)
  channel_analysis:
    channels_to_track:
      - supermercados
      - online
      - conveniencia
      - d2c
      - especializados
    analyze_experience: true
  
  # Market Context settings (NUEVO)
  market_context:
    use_perplexity: true  # Priorizar Perplexity para info actualizada
    include_pestel: true
    include_porter: true
    include_drivers: true

reporting:
  # PDF generation settings
  format: A4
  orientation: portrait
  
  # Required sections for all reports
  required_sections:
    - resumen_ejecutivo
    - mercado
    - competencia
    - sentimiento_reputacion
    - oportunidades_riesgos
    - plan_90_dias
    - anexos
  
  # Quality thresholds
  quality:
    min_hallazgos: 3
    min_oportunidades: 3
    min_riesgos: 3
    min_plan_acciones: 3
    min_kpi_references: 10

logging:
  # Log format and levels
  format: json
  level: INFO
  # Where to store logs
  file: logs/twolaps.log
  # Rotation
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Query frequency options (in days)
query_frequencies:
  daily: 1
  weekly: 7
  biweekly: 14
  monthly: 30
  quarterly: 90

