# Agent-Specific Prompts - Prompts especializados para cada agente

sentiment_agent:
  task: |
    Analiza el sentimiento sobre las marcas en el siguiente texto.
    
    MARCAS A ANALIZAR: {marcas}
    
    TEXTO:
    {texto}
    
    INSTRUCCIONES:
    1. Para cada marca mencionada, determina el sentimiento (-1 negativo, 0 neutral, +1 positivo)
    2. Identifica atributos mencionados: sabor, precio, calidad, sostenibilidad, packaging
    3. Detecta ocasiones de consumo: fiesta, comida, regalo, casual, premium
    4. Evalúa el tono general de la mención
    
    DEVUELVE JSON:
    {{
      "marca": {{
        "score": float,  # -1 a 1
        "tono": "positivo|neutral|negativo",
        "atributos": {{"sabor": score, "precio": score, ...}},
        "ocasiones": ["fiesta", "comida", ...],
        "quote": "fragmento relevante del texto"
      }}
    }}

attributes_agent:
  task: |
    Extrae y clasifica los atributos asociados a cada marca en el contexto FMCG.
    
    MARCAS: {marcas}
    TEXTO: {texto}
    
    ATRIBUTOS A IDENTIFICAR:
    
    1. CALIDAD: premium, estándar, económica, artesanal, industrial
    2. PRECIO: caro, accesible, económico, valor, lujo
    3. SABOR: intenso, suave, equilibrado, único, tradicional
    4. SOSTENIBILIDAD: ecológico, orgánico, local, responsable
    5. PACKAGING: innovador, clásico, premium, práctico
    6. OCASIÓN: celebración, cotidiano, regalo, especial
    7. PERFIL: joven, familiar, profesional, premium, masivo
    
    DEVUELVE JSON:
    {{
      "marca": {{
        "calidad": ["premium", "artesanal"],
        "precio": ["accesible"],
        "sabor": ["equilibrado"],
        "sostenibilidad": [],
        "packaging": ["premium"],
        "ocasion": ["celebración", "regalo"],
        "perfil": ["premium", "profesional"]
      }}
    }}

competitive_agent:
  task: |
    Analiza el posicionamiento competitivo relativo entre marcas.
    
    DATOS DE SOV: {sov_data}
    DATOS DE SENTIMIENTO: {sentiment_data}
    MENCIONES POR MARCA: {menciones}
    
    ANÁLISIS REQUERIDO:
    
    1. POSICIONAMIENTO: ¿Qué marca domina? ¿Cuál es el orden de preferencia?
    2. GAPS COMPETITIVOS: ¿Qué NO se menciona sobre cada marca?
    3. FORTALEZAS: ¿Qué atributos positivos destaca cada marca?
    4. DEBILIDADES: ¿Qué criticidades o ausencias se notan?
    5. COMPARACIONES DIRECTAS: ¿Cómo se comparan marca A vs marca B?
    
    DEVUELVE JSON estructurado con hallazgos específicos y cuantificados.

strategic_agent:
  task: |
    Eres un consultor de estrategia senior (McKinsey/BCG).
    Analiza los siguientes datos de mercado y competencia.

    DATOS CUANTITATIVOS (SOV):
    {sov_data}

    DATOS DE SENTIMIENTO (Score -1 a 1):
    {sentiment_data}

    DATOS DE POSICIONAMIENTO COMPETITIVO:
    {competitive_data}

    DATOS DE TENDENCIAS:
    {trends_data}

    INSTRUCCIONES:
    Basándote EXCLUSIVAMENTE en los datos proporcionados:
    1. Identifica las 3 OPORTUNIDADES estratégicas más importantes.
    2. Identifica los 3 RIESGOS estratégicos más críticos.

    Para cada OPORTUNIDAD, formato JSON:
    {{
      "titulo": "Título accionable de la oportunidad",
      "descripcion": "Explicación de 2 líneas de la oportunidad",
      "datos_soporte": "KPI específico que justifica esto (ej: 'Marca X tiene SOV 5% pero Sentimiento 0.9')",
      "impacto": "alto|medio|bajo",
      "esfuerzo": "alto|medio|bajo",
      "prioridad": "alta|media|baja"
    }}

    Para cada RIESGO, formato JSON:
    {{
      "titulo": "Título claro del riesgo",
      "descripcion": "Explicación de 2 líneas del impacto potencial",
      "datos_soporte": "KPI específico que justifica esto (ej: 'Líder tiene SOV 54% pero Sentimiento 0.00')",
      "probabilidad": "alta|media|baja",
      "severidad": "alta|media|baja",
      "mitigacion": "Sugerencia de mitigación accionable"
    }}

    DEVUELVE UN ÚNICO OBJETO JSON con las claves "oportunidades" y "riesgos".

synthesis_agent:
  task: |
    Eres el Director de Estrategia. Tu trabajo es sintetizar todos los análisis en una narrativa central (el "So What?").
    Analiza los siguientes KPIs y hallazgos estratégicos.

    KPIs CUANTITATIVOS (SOV, Menciones):
    {quantitative_results}

    KPIs DE SENTIMIENTO:
    {sentiment_results}

    ANÁLISIS ESTRATÉGICO (Oportunidades y Riesgos):
    {strategic_results}

    INSTRUCCIONES:
    Usando la metodología de consultoría (Situación, Complicación, Pregunta), genera la narrativa central del informe.
    
    DEVUELVE UN ÚNICO OBJETO JSON con esta estructura:
    {{
      "situacion": "Párrafo de 2-3 líneas describiendo el estado actual del mercado (ej: 'El mercado está dominado por X, con un volumen de Y...')",
      "complicacion": "Párrafo de 2-3 líneas describiendo la tensión o el problema principal (ej: 'A pesar de su dominio en SOV (54%), el líder sufre un sentimiento nulo (0.00), lo que abre una brecha...')",
      "pregunta_clave": "La pregunta de negocio fundamental que el cliente debe responder (ej: '¿Cómo puede el líder capitalizar su visibilidad para construir afinidad, o cómo pueden los competidores explotar esta debilidad?')"
    }}

executive_agent:
  task: |
    Genera un informe ejecutivo completo de consultoría basándote en todos los análisis previos.
    
    DATOS DISPONIBLES:
    
    KPIs Cuantitativos:
    {quantitative_results}
    
    Análisis de Sentimiento:
    {sentiment_results}
    
    Atributos de Marca:
    {attributes_results}
    
    Posicionamiento Competitivo:
    {competitive_results}
    
    Tendencias:
    {trends_results}
    
    Oportunidades y Riesgos:
    {strategic_results}
    
    Contexto Histórico (periodos similares):
    {historical_context}
    
    GENERA EL INFORME CON ESTAS SECCIONES EXACTAS:
    
    1. resumen_ejecutivo:
       - 3-5 hallazgos clave del periodo (bullets)
       - Cada hallazgo debe citar KPIs específicos
       - Prioriza por impacto para el negocio
    
    2. mercado:
       - Estado general del mercado en el periodo
       - Volumen de conversación (menciones totales)
       - Principales temas de discusión
       - Comparación con periodo anterior (si hay contexto histórico)
    
    3. competencia:
       - Tabla de SOV por marca
       - Análisis de líderes vs. seguidores
       - Comparativas directas marca vs marca
       - Gaps y oportunidades competitivas
    
    4. sentimiento_reputacion:
       - Sentimiento por marca (con scores)
       - Atributos asociados por marca
       - Ocasiones de consumo mencionadas
       - Evolución vs. periodo anterior
    
    5. oportunidades_riesgos:
       - Oportunidades: lista priorizada (Alta/Media/Baja)
       - Riesgos: lista con severidad y mitigación
       - Quick wins identificados
    
    6. plan_90_dias:
       - 3-5 iniciativas priorizadas
       - Para cada una: QUÉ, POR QUÉ (datos), CÓMO (pasos), CUÁNDO (timeline)
       - Priorización RICE: Reach, Impact, Confidence, Effort
       - Timeline sugerido (Mes 1, Mes 2, Mes 3)
    
    FORMATO DE SALIDA: JSON estructurado
    
    RECUERDA:
    - Cita SIEMPRE los KPIs y datos específicos
    - Sé accionable y específico
    - Evita vaguedades
    - Tono ejecutivo y consultivo
    - Longitud: completo pero conciso

trends_agent:
  task: |
    Detecta tendencias emergentes y cambios significativos comparando con periodos anteriores.
    
    DATOS PERIODO ACTUAL:
    {current_period_data}
    
    DATOS HISTÓRICOS:
    {historical_periods}
    
    ANÁLISIS REQUERIDO:
    
    1. TOPIC SHIFT: ¿Qué temas nuevos aparecen? ¿Cuáles desaparecen?
    2. MARCAS EMERGENTES: ¿Qué marcas ganan visibilidad?
    3. CAMBIOS DE SENTIMIENTO: ¿Qué marcas mejoran/empeoran?
    4. NUEVOS ATRIBUTOS: ¿Qué características se mencionan por primera vez?
    5. CAMBIOS EN SOV: ¿Quién gana/pierde share of voice?
    
    Para cada tendencia detectada:
    - Cuantificar el cambio (%, absolutos)
    - Indicar dirección (↑ crecimiento, ↓ decrecimiento, ↔ estable)
    - Evaluar significancia (Alta/Media/Baja)
    
    DEVUELVE JSON con tendencias priorizadas.

